### ISSUE TITLE
Update Wowza to latest version (deployment automation)

### ISSUE THREAD

**Issue by tingulfsen** [sul-dlss/dlss-wowza#19]
We're currently running Wowza version 4.1.2 on the server. Let's upgrade to the latest version (4.4.1). Amongst other things this will enable a (license-free) REST client interface to server management, which will allow us to restart individual wowza applications gracefully after deploying a new jar via puppet.

**Comment by ndushay** [comment]
"The REST API is included with 4.2 whereas earlier 4.x versions required preview approval and installation."

Also, see

https://www.wowza.com/forums/content.php?644-How-to-access-documentation-for-Wowza-Streaming-Engine-REST-API

https://www.wowza.com/forums/content.php?711-How-to-use-cURL-to-query-Wowza-REST-API

https://www.wowza.com/forums/content.php?738-rest-api-query-examples

**Comment by peetucket** [comment]
No longer necessary since puppet will restart wowza on deploy.
