### ISSUE TITLE
Set Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by tingulfsen** [sul-dlss/dlss-wowza#24]
Setting the Access-Control-Allow-Origin header correctly is necessary in order to stream video via the Dash player (non-Safari/non-HLS). This is a pre-requisite for sul-dlss/sul-embed#581 to be fulfilled.

There is a server-wide configuration XML file in conf/crossdomain.xml:

https://www.wowza.com/forums/showthread.php?16296-How-to-Access-Control-Allow-Origin-to-playlist-m3u8-file&p=83311#post83311

However, if we edit that file, we may break Flash streaming, which is necessary for the migrated sul-streaming content (collections.stanford.edu etc.) to work until that material is accessioned and re-encoded:

https://www.wowza.com/forums/showthread.php?45081-The-function-of-crossdomain-xml

I believe we may be able to set this header explicitly in our own Java code, thereby hopefully overriding the server-wide default in crossdomain.xml for non-Flash content, while still allowing Flash content to stream correctly:

https://www.wowza.com/forums/showthread.php?16296-How-to-Access-Control-Allow-Origin-to-playlist-m3u8-file&p=83316#post83316

**Comment by jkeck** [comment]
@tingulfsen I thought the `crossdomain.xml` file is used **only** for flash (I could be totally wrong about that).  I thought I saw somewhere in the `Application.xml` that we could said CORS headers for a specific application (and maybe somewhere in the UI where we could set it as well), but my memory is vague.

**Comment by tingulfsen** [comment]
Earlier today, we merged #25 because we thought the right way to make Wowza set the right header would be to alter the plugin code. Instead, it turns out that altering the XML in the application-specific XML appears to be the easier approach:

https://www.wowza.com/forums/content.php?773-How-to-enable-cross-origin-resource-sharing-(CORS)-for-HTTP-based-streams#configure_props

We need to 
- [x] Back out the changes introduced in #25.
- [x] Upgrade Wowza to the latest version (DevOps is working on this).
- [x] Confirm that changing Application.xml as described above will work.

**Comment by tingulfsen** [comment]
I think that Application.xml is the right place to make any changes to Wowza's configuration. Other than that, this ticket is done.
