### ISSUE TITLE
Puppet script updates to allow for easier automated updates of wowza

### ISSUE THREAD

**Issue by tingulfsen** [sul-dlss/dlss-wowza#35]
We would like to automatically make Puppet set up the server with everything we need when we install/reinstall Wowza. This is a (non-exhaustive) list of actions such a script would take:
- Install the latest version of dlss-wowza
- Create WowzaStreamingEngine/applications/stacks_test/sharedobjects/_definst_/ (empty directory)
- Create WowzaStreamingEngine/conf/stacks_test/
- Copy our current WowzaStreamingEngine/conf/stacks_test/Application.xml
- Copy our current WowzaStreamingEngine/conf/Server.xml (server-specific)
- Copy our current WowzaStreamingEngine/conf/VHost.xml (server-specific)
- Make a symbolic link to the data directory

We should also document the process once we're done with it, in some form.

This is fallout from my conversations with @eefahy

**Comment by ndushay** [comment]
Here's a pass at current setup:

### Wowza localization:

#### All Wowza instances
- `Server.xml` (`Server/RESTInterface/IPWhiteList`)
- `VHost.xml` (`/VHost/HosPortList/HostPort/IpAddress`)
- `conf/log4j.properties`
- puppet puts stuff in `lib` dir
- puppet rotates logs from `logs` dir

#### Wowza prod:
- `stacks` Wowza application
  - has its own `Application.xml` in `conf/stacks/Application.xml`
  - content in `/stacks`
- `sul-streaming` Wowza application
  - has its own `Application.xml` in `conf/sul-streaming/Application.xml`
  - content in `/data/sul-streaming` 

#### Wowza stage:
- `stacks-test` Wowza application  (could be renamed `stacks`)
  - has its own `Application.xml` in `conf/stacks_test/Application.xml`
  - content in `/stacks` (or could be - symlinked from `content/stacks_test/` currently)

#### Wowza dev:

no Wowza applications we care for puppet to maintain

Once we settle all this down, it should go in devops docs.

@tingulfsen

**Comment by tingulfsen** [comment]
Let's be consistent and make both the prod and stage boxes use the application name `stacks` and make both of them point to `/stacks` for content.

**Comment by ndushay** [comment]
Note:   Wowza-stage  now has  properly configured `stacks` app, so that should be used instead of `stacks_test`, which will be removed.

**Comment by ndushay** [comment]
`stacks`  from stage should be just what we need in prod except
- property set for  `sul-stacks-test`  that needs to be   just  `stacks` for prod
- property from stage points to `embed-dev` and prod needs to just be `embed`

**Comment by ndushay** [comment]
we believe we have puppet working properly on -dev.    the wowza applications appear and the log4j.properties works, and nothing in error logs.

Next:  same for -stage, then puppet changes for prod to use silent installer and away we go!

**Comment by ndushay** [comment]
puppet stuff tweaked a bit more as we installed it on prod.  w00t!
