### ISSUE TITLE
Do we still need Wowza  CORS configurations?

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/dlss-wowza#40]
Now that we're using flash/rtmp as a fallback I wonder if we should remove our CORS configurations for the HLS/DASH streams.

A main motivation for adding the CORS headers was the fact that we were redirecting through Stacks.  

Now that we're not doing all http streaming (i.e. rtmp) CORS doesn't come into play for all of our streaming formats.  Given that fact, should we just remove the CORS configurations from wowza all together?  This should allow us to least view **public** media from our development machines and would remove some additional complexity on the wowza side.

_FWIW, I think we should keep the CORS headers as-is on Stacks as that locks down the minting of media tokens to the SUL Embed service._

**Comment by ndushay** [comment]
I think we configure CORS per Wowza Application, if not Wowza instance.  We could experiment with wowza-dev ...

**Comment by ndushay** [comment]
If they are not needed, we should remove them from README info and from DevOpsDocs and anywhere else we documented the need for them.

**Comment by ndushay** [comment]
they are set for /Root/Application/HTTPStreamer   which implies not RTMP, so maybe they CAN go ...

**Comment by ndushay** [comment]
@jkeck will test if non-safari playing HLS via videojs requires CORS headers or not by running against stacks wowza app without plugin.

**Comment by ndushay** [comment]
@jkeck will comment further here (or perhaps in DevOpsDocs https://github.com/sul-dlss/DevOpsDocs/blob/master/projects/media/wowza/wowza_server_checklist.md  and/or https://github.com/sul-dlss/dlss-wowza  README), but basically, YES, we do still need the  Wowza application to have property /Root/Application/HTTPStreamer  httpCORSHeadersAddMain  set.
