### ISSUE TITLE
Create a UAT environment for wowza?

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/dlss-wowza#48]
Now that we have a Stacks/Embed/PURL UAT environment, it may make sense for us to have a streaming server environment (given that the CORS headers need to specify an embed environment that can send credentialed requests).

Once we move to production with media we will not be able to use the production wowza instance to server the UAT environment.

**Comment by ndushay** [comment]
I wonder if we can do a UAT wowza application.  We are read only for stacks content on the Wowza box, so adding another application with a different CORS endpoint may work just fine.

**Comment by hannahfrost** [comment]
Is this the same thing as media file pre-flight that I mentioned at stand-up yesterday?

**Comment by jkeck** [comment]
@hannahfrost I believe that this would be different.  Without doing this, once we are in production we would not have a good way to play media in the UAT environment (since the production wowza server is locked down to the production embed/stacks environment).

One thing that I was thinking, could we just create another application on the production wowza server that had all the same plugins as our `stacks` wowza app, but could point to the UAT environment.  Assuming that it wouldn't be a performance concern, it could allow to have media playing in the PURL/Embed/Stacks UAT environment without needing to purchase an additional license.

Ultimately, that's what we want to do for the media file pre-flight (just put another app on a wowza server) but it might end up living on a non-production server.

**Comment by cbeer** [comment]
Opening the production wowza to the UAT environment makes sense; it's the same pattern as with the imageserver.

**Comment by jkeck** [comment]
lol, sorry @ndushay I didn't see your comment above.

**Comment by ndushay** [comment]
@jkeck: great minds think alike, I guess.

**Comment by ndushay** [comment]
Also, I agree with Jessie that this is different from coming up with a way to vet media depositing formats.  (Is that a separate ticket somewhere?)

**Comment by ndushay** [comment]
Plans:
- [x] create uat  wowza application on wowza prod, using puppet and so forth  (sul-dlss/puppet#1061)
- [x] update devopsdocs re: new wowza app on prod. (sul-dlss/DevOpsDocs/pull/66)
