### ISSUE TITLE
[Fall 2023 Wowza upgrade] Make sure streaming video examples for at least one of each type of access restriction from the example spreadsheet works

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/dlss-wowza#61]
should we block this on #58 and #60?

Using the newly built `sul-streamengine-stage`...

see also https://github.com/sul-dlss/operations-tasks/issues/3514

part of https://github.com/sul-dlss/dlss-wowza/issues/57

In particular, test: world readable, Stanford restricted, and location restricted videos.

[list of media object examples with various rights combos](https://docs.google.com/spreadsheets/d/1TW9upk7g67BWbbvIVHKyY45SSJCgKkccKLT_L80-8vk/edit#gid=0)

**Comment by mjgiarlo** [comment]
Previously was blocked by #58 & #60

**Comment by mjgiarlo** [comment]
Part of this testing is updating shared_configs to point at sul-embed-stage to the new wowza box.

**Comment by jmartin-sul** [comment]
@andrewjbtw performed this testing against the new wowza server this week and last, things worked as expected, closing.

we didn't end up blocking on #58 or #60.
