### ISSUE TITLE
block requests other than HLS and rtmp  (not using Dash at this time)

### ISSUE THREAD

**Issue by tingulfsen** [sul-dlss/dlss-wowza#8]
Currently, the server is blocked from serving flash etc. because of the Application.xml (configuration) file.

I think we should implement the other Wowza API methods that are called someone attempts to start a session of other types than those we support, and reject those sessions outright.

This will serve as a "double safety" in case we somehow botch the XML configuration at some later time.

**Comment by peetucket** [comment]
need to ensure we can still allow flash video for the sul-streaming migrated content

**Comment by ndushay** [comment]
in production, blocked by sul-dlss/media#111.

**Comment by ndushay** [comment]
sul-streaming will be fine, as it doesn't use the dlss-wowza plugin.

**Comment by ndushay** [comment]
closing;  risk is too low to worry about this.
