### ISSUE TITLE
ensure wowza plugin can handle special chars in file names

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dlss-wowza#9]
probably a matter of url escaping media filenames as well as being prepared for utf-8 charset.

ensure that roundtrip of   stacks-redirect --> wowza --> stacks token verification -->  user   works for weird chars in filenames

See https://github.com/sul-dlss/media/wiki/Examples-of-files-deposited-by-ETD-users,-special-characters-and-media-files  for examples.

**Comment by ndushay** [comment]
waiting on #5

**Comment by jmartin-sul** [comment]
is there more to do than making sure that we URL encode the appropriate query parameters and path components when the wowza plugin is talking to stacks?

other areas to consider:
- parameter retrieval (file name, token string) in the wowza plugin (the "stacks-redirect --> wowza" part)
- parameter retrieval in the stacks rails app (the "wowza --> stacks token verification" part, which @jkeck suggests testing in the stacks media controller routing spec, if at all)

seems like the "stacks token verification --> user" part is just wowza interpreting the token verification response from stacks, and hopefully shouldn't involve encoding issues?

**Comment by ndushay** [comment]
I think when #18 is merged, this can be marked done, give or take an end-to-end verification on weird file names?
